### ISSUE TITLE
代码看着太乱

### ISSUE THREAD

**Issue by wanggangkun** [imiyoo2010/teye_scanner_for_book#6]
有第六章扫描器完整能运行的代码吗？

**Comment by imiyoo2010** [comment]
你好，这块是有什么问题？如果读者都有需求的话，我会考虑把扫描器的完整代码重构放出，已上传的代码只是本地端的运行实例。

**Comment by aiwennba** [comment]
能否把代码重构放出啊？

**Comment by aiwennba** [comment]
@imiyoo2010    有需求，能否把代码重构放出.....?

**Comment by imiyoo2010** [comment]
当然可以啊，之前写书有点仓促，加之时间有点紧，我收集和梳理下，希望你也可以加入帮忙。

**Comment by 90Fox** [comment]
跪求完整版的，买了书看了好懵逼。

**Comment by lazybootsafe** [comment]
沒有完整代碼，看這份和看書好亂...

**Comment by moss1993** [comment]
书+完整版跟配哦

**Comment by wokimi** [comment]
看书和代码摸不着头脑，有点乱

**Comment by imiyoo2010** [comment]
可以具体反馈问题，哪块乱，不然你让作者怎么改进。
