### ISSUE TITLE
建议作者将一份可运行的源码贴出来

### ISSUE THREAD

**Issue by zsdlove** [imiyoo2010/teye_scanner_for_book#9]
要有分享精神，薄薄的一本书，要加60多，连一份能运行的源码都没有。这个也太坑爹了吧，让新手学习的信心都没有了。

**Comment by wokimi** [comment]
根据作者的源码可以复现出前六章的可运行代码

**Comment by imiyoo2010** [comment]
这个话就不太认可了，可以运行的代码已经上传，有问题也欢迎交流；我觉得有耐心看完不可能跑不起来这个程序
